// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var $canvas, canvas, ctx, img, params, textImageURL, up;
    params = {};
    window.location.search.substring(1).split("&").forEach(function(e) {
      var param;
      param = e.split("=");
      return params[param[0]] = param[1];
    });
    $canvas = $("#canvas");
    canvas = $canvas.get(0);
    ctx = canvas.getContext("2d");
    img = new Image();
    img.onload = function() {
      var point;
      point = 120;
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);
      ctx.fillStyle = "#ffffff";
      ctx.strokeStyle = "#000000";
      ctx.font = "bold " + point + "px Oswald";
      $canvas.on("mousedown", function(e) {
        return ctx.fillText("LGTM", e.offsetX, e.offsetY);
      });
      return $("#up").on("click", function(e) {
        return up(canvas.toDataURL());
      });
    };
    img.src = params["u"];
    up = function(dataURL) {};
    return textImageURL = function(height) {
      canvas = $("<canvas>").get(0);
      canvas.width = height * 5;
      canvas.height = height;
      ctx = canvas.getContext("2d");
      ctx.fillStyle = "#ffffff";
      ctx.strokeStyle = "#000000";
      ctx.font = "bold " + height + "px Oswald";
      ctx.fillText("LGTM", 0, height);
      return canvas.toDataURL("image/png");
    };
  });

}).call(this);

//# sourceMappingURL=main.js.map
